name: trivy-scan-CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container: 
      image: ixxel/multi-tools-alpine:latest
    steps:
    - name: Run trivy for CVE scan
      uses: ixxeL-actions/trivy-scan@main
      with:
        scan-type: 'image'
        image-ref: 'ixxel/multi-tools-alpine:latest'
        scan-ref: '/usr/local/bin'

      
