name: trivy-scan-CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container: 
      image: ixxel/multi-tools-alpine:latest
    steps:
    - name: Trivy image scan
      uses: ixxeL-actions/trivy-scan@main
      with:
        scan-type: 'image'
        image-ref: 'ixxel/multi-tools-alpine:latest'
        security-checks: 'vuln,config'
        output: 'result'
        format: 'template'
        template: '{{- $critical := 0 }}{{- $high := 0 }}{{- $med := 0 }}{{- $low := 0 }}{{- $unknown := 0 }}
                  {{- range . }}{{- range .Vulnerabilities }}
                  {{- if  eq .Severity "CRITICAL" }}
                    {{- $critical = add $critical 1 }}
                  {{- end }}
                  {{- if  eq .Severity "HIGH" }}
                    {{- $high = add $high 1 }}
                  {{- end }}
                  {{- if  eq .Severity "MEDIUM" }}
                    {{- $med = add $med 1 }}
                  {{- end }}
                  {{- if  eq .Severity "LOW" }}
                    {{- $low = add $low 1 }}
                  {{- end }}
                  {{- if  eq .Severity "UNKNOWN" }}
                    {{- $unknown = add $unknown 1 }}
                  {{- end }}
                  {{- end }}
                  {{- end }}
                  Critical: {{ $critical }} High: {{ $high }} Medium: {{ $med }} Low: {{ $low }} Unknown: {{ $unknown }}'

      
