name: trivy-scan-CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container: 
      image: ixxel/multi-tools-alpine:latest
    steps:
    - name: Trivy image scan
      uses: ixxeL-actions/trivy-scan@main
      with:
        scan-type: 'image'
        image-ref: 'ixxel/multi-tools-alpine:latest'
        security-checks: 'vuln,config'
        output: 'result'

      
