name: unit-tests-img-CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container: 
      image: ixxel/multi-tools-alpine:latest
    steps:
    - name: Run trivy for CVE scan
      uses: ixxeL2097/action-trivy@main
      with:
        scan-type: 'image'
        image-ref: 'ixxel/multi-tools-alpine:latest'
      
